/**
 * goals.ts — TYPE-ONLY sketch of the future Goals / Progress Tracking system.
 *
 * ⚠️ INERT FOUNDATION. Nothing imports this; it adds NO runtime code and changes NO
 *    behavior (types are erased at compile time). It pins the shape of the
 *    goals-first product so the eventual layer (helpers → Supabase → Goals tab) has
 *    a target. See docs/GOALS_FIRST_SYSTEM_PLAN.md.
 *
 * The model (doctrine: generic core, pack content on top):
 *   Goal (persistent object) → recurring update window → GoalUpdate (a structured
 *   response). A Goal is NOT a task and is never "done" in the task sense — it
 *   progresses over time. The update layer REUSES the existing structured-response
 *   stack: a GoalUpdate's answers are a StructuredAnswerMap, and update tasks are
 *   generated by the existing questionnaire generation.
 *
 * IMPORTANT: this reuses existing generic types (StructuredAnswerMap) and the
 * RoleKey string alias rather than inventing parallels, and does NOT widen the
 * closed `Role` union. No app screen imports this; no Supabase; no UI.
 */

import type { StructuredAnswerMap } from './structuredResponses';
import type { RoleKey } from './rolePack';

/** How often a goal expects an update. 'custom' carries a caller-defined period. */
export type GoalCadence = 'daily' | 'weekly' | 'monthly' | 'custom';

/** A goal's lifecycle status. Distinct from the task state machine. */
export type GoalStatus = 'active' | 'completed' | 'archived';

/**
 * A persistent goal/progress object. Lives over time; tracked by current vs target.
 * `ownerRole` uses RoleKey (pack-shaped) — a goal can be owned by a role; a future
 * person-owned variant would add an ownerMemberId. Numeric value is optional so a
 * milestone/boolean goal (no number) is also expressible.
 */
export interface Goal {
  /** Stable id (org-unique). */
  id:          string;
  /** Org scope. */
  orgId:       string;
  /** Human title / prompt (e.g. 'Recruit 12 new members'). */
  title:       string;
  /** Optional longer description. */
  description?: string;

  /** Owning role (pack-shaped key). A person-owned goal would add ownerMemberId. */
  ownerRole?:    RoleKey;
  ownerMemberId?: string;
  /**
   * The member id that CREATED this goal (audit). Drives the "can I manage this?"
   * rule: an officer may edit/complete/archive only goals they created — a goal
   * assigned to their role by leadership is read-only to them. Leadership/annotator
   * may manage any goal regardless of creator.
   */
  createdBy?:    string;

  /** Optional measurable target + current value (omit for milestone/boolean goals). */
  targetValue?:  number;
  currentValue?: number;
  /** Optional unit label (e.g. 'members', '$', 'hours'). */
  unit?:         string;

  /** How often an update is expected. */
  cadence:       GoalCadence;
  /** For 'custom' cadence: a caller-defined period key/length (days). */
  customPeriodDays?: number;

  status:        GoalStatus;

  /**
   * The structured-response definition id this goal's recurring UPDATES collect
   * (a StructuredResponseDefinition id, e.g. WEEKLY_OFFICER_REPORT_ID). Reuses the
   * existing questionnaire/report form + storage as the update layer. Optional —
   * a goal with no update definition simply generates no update tasks.
   */
  updateDefinitionId?: string;

  /** Optional reviewer role + visibility (mirrors the submissions read model). */
  reviewerRole?: RoleKey;
  visibleTo?:    RoleKey[] | 'all';

  /** Optional later links (event/committee/category) — reserved, unused now. */
  categoryKey?:  string;
  linkedEventId?: string;
}

/**
 * One update against a goal for a period — a structured response plus the value it
 * reported. Reuses StructuredAnswerMap (the existing form answers) so the Task
 * Detail form + submission storage carry it unchanged.
 */
export interface GoalUpdate {
  /** The goal this update belongs to. */
  goalId:      string;
  /** Stable period key for the update window (e.g. '2026-W23', '2026-06'). */
  period:      string;
  /** The update task that surfaced this update (the existing task model). */
  taskId?:     string;
  /** Reported current value for the goal at this update (optional for text-only). */
  value?:      number;
  /** The structured answers (what changed / need help / announcement / no-update). */
  answers:     StructuredAnswerMap;
  /** True if the responder marked "no update this period". */
  noUpdate?:   boolean;
  /** True if this update requests the goal be marked complete (review, not auto). */
  requestsCompletion?: boolean;
  /** Who submitted (role key) + when (ISO). */
  submittedByRole?: RoleKey;
  submittedAt?: string;
}

/**
 * A goal-creation TEMPLATE/default a pack ships (the goal analog of a questionnaire
 * template). Reserved shape for pack content — inert. The update FORM a goal uses is
 * still a StructuredResponseDefinition (reused), referenced by id.
 */
export interface GoalTemplate {
  /** Stable id. */
  id:            string;
  /** Human label (e.g. 'Officer Term Goal'). */
  label:         string;
  /** Default cadence for goals created from this template. */
  defaultCadence: GoalCadence;
  /** The structured-response definition id used for this goal's updates. */
  updateDefinitionId: string;
}
